### ISSUE TITLE
Put the follower section first

### ISSUE THREAD

**Issue by dittaeva** [joticajulian/steem-activity#3]
I'd put the follower section first, as it is by far the most interesting.

**Comment by joticajulian** [comment]
I put the activity of the user first for one reason:
Suppose you ask for @guttormf. It shows your activity and next your followers... 
Next you want to know the activity of ONE of your followers, for instance @beanz, then you ask for him and **you will see his activity first** (you don't want to see the follower section of @beanz, but his activity).
This is the reason.

I think I need to add buttons to start the follower section and the user section. What do you think?

**Comment by dittaeva** [comment]
I understand. I think buttons could be useful.
