### ISSUE TITLE
Logo Proposal for SteemActivity

### ISSUE THREAD

**Issue by radudangratian** [joticajulian/steem-activity#6]
Hello! I made a logo for your project.I hope you will like it.Below you can find the Gdrive with all the files that you need.Regards!

![logopng](https://user-images.githubusercontent.com/34451833/38043967-1cf6ef06-32c1-11e8-8f51-4882e17a3fda.png)

https://drive.google.com/open?id=1vTGA0XHvmjpMbNy4v2ugi0jwUEXEeHTV

**Comment by joticajulian** [comment]
thanks! merged
